force-app/main/default/objects/Transaction_Close_Event__e/Transaction_Close_Event__e.object-meta.xml
<CustomObject>
    <description>Notifications for the Transaction Close Actions component</description>
    <label>Transaction Close Event</label>
    <pluralLabel>Transaction Close Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_Close_Event__e/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Close_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>&quot;Close&quot; or &quot;Receipt&quot;</description>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TA_TRX_PublishCloseEventAU.cls
@NamespaceAccessible
public with sharing class TA_TRX_PublishCloseEventAU implements agrec.TriggerAction.AfterUpdate {

    private static final String EVENT_TYPE_CLOSE = 'Close';

    @TestVisible
    private List<Database.SaveResult> saveResults = new List<Database.SaveResult>();
    private Map<Id, Transaction_Close_Event__e> closeEventsByTransactionId;

    private List<TREX1__Transaction__c> newList;
    
    @NamespaceAccessible
    public void afterUpdate(List<TREX1__Transaction__c> newList, List<TREX1__Transaction__c> oldList) {
        System.debug(':::: fired TA_TRX_PublishCloseEventAU');
        this.newList = newList;
        saveResults = EventBus.publish( buildEvents().values() );
        System.debug('eventMap --> ' + closeEventsByTransactionId);
    }

    private Map<Id, Transaction_Close_Event__e> buildEvents() {
        closeEventsByTransactionId = new Map<Id, Transaction_Close_Event__e>();
        for (TREX1__Transaction__c trx : newList) {
            closeEventsByTransactionId.put(trx.Id, createCloseEvent(trx.Id));
        }
        return closeEventsByTransactionId;
    }

    private static Transaction_Close_Event__e createCloseEvent(Id transactionId) {
        Transaction_Close_Event__e event = new Transaction_Close_Event__e();
        event.Record_ID__c = transactionId;
        event.Type__c = EVENT_TYPE_CLOSE;
        return event;
    }

}