force-app/main/default/objects/Transaction_Close_Event__e/Transaction_Close_Event__e.object-meta.xml
<CustomObject>
    <description>Notifications for the Transaction Close Actions component</description>
    <label>Transaction Close Event</label>
    <pluralLabel>Transaction Close Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_Close_Event__e/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Close_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>&quot;Close&quot; or &quot;Receipt&quot;</description>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TA_CDL_PublishReceiptEventAI.cls
@NamespaceAccessible
public with sharing class TA_CDL_PublishReceiptEventAI implements agrec.TriggerAction.AfterInsert {

    @TestVisible
    private List<Database.SaveResult> saveResults;
    
    public void afterInsert(List<ContentDocumentLink> newList) {
        List<Transaction_Close_Event__e> events = new List<Transaction_Close_Event__e>();
        for (ContentDocumentLink cdl : newList) {
            Transaction_Close_Event__e event = new Transaction_Close_Event__e();
            event.Record_ID__c = cdl.LinkedEntityId;
            event.Type__c = 'Receipt';
            events.add(event);
        }
        saveResults = EventBus.publish(events);
    }

}