force-app/main/default/objects/Traction_Rec_Receipt_Setting__mdt/Traction_Rec_Receipt_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for the Send Receipt action in the Transaction Close Actions component for Traction Rec payment pages</description>
    <label>Traction Rec Receipt Setting</label>
    <pluralLabel>Traction Rec Receipt Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Traction_Rec_Receipt_Setting__mdt/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <description>The name of the email template to send with the attached receipt</description>
    <inlineHelpText>The name of the email template to send with the attached receipt</inlineHelpText>
    <label>Email Template Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Traction_Rec_Receipt_Setting__mdt/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <description>The name for receipt attachment files. If blank, the Title of the related ContentDocument is used.</description>
    <inlineHelpText>The name for receipt attachment files. If blank, the Title of the related ContentDocument is used.</inlineHelpText>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Traction_Rec_Receipt_Setting__mdt/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <description>The email address of the sender. Must be a verified Org Wide Email Address. If blank, the sender is the running user.</description>
    <inlineHelpText>The email address of the sender. Must be a verified Org Wide Email Address. If blank, the sender is the running user.</inlineHelpText>
    <label>From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReceiptSender_Test.cls
@IsTest
private class ReceiptSender_Test {
    
    @IsTest
    static void testSend() {
        Contact ct = agrec.TestDataFactory.createContacts(1).get(0);
        insert ct;

        TREX1__Transaction__c trx = agrec.TestDataFactory.createTransaction(ct.Id);
        insert trx;

        createReceipt(trx.Id);

        Test.startTest();
        ReceiptSender sender = new ReceiptSender(trx.Id);
        String result = sender.send();
        Test.stopTest();

        System.Assert.areEqual('success', result, 'Should have received a successful send result');
    }

    @IsTest
    static void testSendReceiptWithDefaultFileName() {
        EmailTemplate emailTemplate = [SELECT Name FROM EmailTemplate LIMIT 1];

        Traction_Rec_Receipt_Setting__mdt settings = new Traction_Rec_Receipt_Setting__mdt();
        settings.Email_Template_Name__c = emailTemplate.Name;
        settings.File_Name__c = 'TestReceipt';
        ReceiptSender.receiptSettings = settings;

        Contact ct = agrec.TestDataFactory.createContacts(1).get(0);
        insert ct;

        TREX1__Transaction__c trx = agrec.TestDataFactory.createTransaction(ct.Id);
        insert trx;

        createReceipt(trx.Id);

        Test.startTest();
        ReceiptSender sender = new ReceiptSender(trx.Id);
        String result = sender.send();
        Test.stopTest();

        System.Assert.areEqual('success', result, 'Should have received a successful send result');
    }

    @IsTest
    static void testSendWithOrgWideEmailAddress() {
        List<OrgWideEmailAddress> addresses = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 1];

        if (addresses.isEmpty()) {
            return;
        }

        Traction_Rec_Receipt_Setting__mdt settings = new Traction_Rec_Receipt_Setting__mdt();
        settings.From_Address__c = addresses[0].Address;
        ReceiptSender.receiptSettings = settings;

        Contact ct = agrec.TestDataFactory.createContacts(1).get(0);
        insert ct;
        TREX1__Transaction__c trx = agrec.TestDataFactory.createTransaction(ct.Id);
        insert trx;

        ReceiptSender sender = new ReceiptSender(trx.Id);
        Test.startTest();
        OrgWideEmailAddress result = sender.getFromAddress();
        Test.stopTest();

        System.Assert.areEqual(addresses[0].Id, result.Id, 'Should have received Org Wide Email Address ' + addresses[0].Address);
    }

    @IsTest
    static void testSendWithInvalidRecordId() {
        Id fakeId = agrec.TriggerTestUtility.getFakeId(TREX1__Transaction__c.SObjectType);

        Test.startTest();
        try {
            ReceiptSender sender = new ReceiptSender(fakeId);
            String result = sender.send();
            System.Assert.fail('Should have received an exception for no transaction found');
        } catch (Exception e) {
            System.Assert.isNotNull(e.getMessage(), 'Should have received an exception message');
        }
        Test.stopTest();
    }

    @IsTest
    static void testSendWithNullRecordId() {
        Test.startTest();
        try {
            ReceiptSender sender = new ReceiptSender(null);
            String result = sender.send();
            System.Assert.fail('Should have received an exception for no transaction found');
        } catch (Exception e) {
            System.Assert.isNotNull(e.getMessage(), 'Should have received an exception message');
        }
        Test.stopTest();
    }

    @IsTest
    static void testSendWithNoReceipt() {
        Boolean isOrgEmailEnabled = ReceiptSender.isOrgEmailEnabled();
        
        Contact ct = agrec.TestDataFactory.createContacts(1).get(0);
        insert ct;

        TREX1__Transaction__c trx = agrec.TestDataFactory.createTransaction(ct.Id);
        insert trx;

        Test.startTest();
        try {
            ReceiptSender sender = new ReceiptSender(trx.Id);
            String result = sender.send();
            System.Assert.fail('Should have received an exception for the lack of receipt');
        } catch (Exception e) {
            System.Assert.isNotNull(e.getMessage(), 'Should have received an exception message');
        }
        Test.stopTest();
    }

    @IsTest
    static void testInvalidEmailTemplate() {
        Traction_Rec_Receipt_Setting__mdt settings = new Traction_Rec_Receipt_Setting__mdt();
        settings.Email_Template_Name__c = 'RuhRoh';
        ReceiptSender.receiptSettings = settings;

        Contact ct = agrec.TestDataFactory.createContacts(1).get(0);
        insert ct;

        TREX1__Transaction__c trx = agrec.TestDataFactory.createTransaction(ct.Id);
        insert trx;

        createReceipt(trx.Id);

        Test.startTest();
        try {
            ReceiptSender sender = new ReceiptSender(trx.Id);
            String result = sender.send();
            System.Assert.fail('Should have received an exception for the invalid template name');
        } catch (Exception e) {
            System.Assert.isNotNull(e.getMessage(), 'Should have received an exception message');
        }
        Test.stopTest();
    }

    private static ContentDocumentLink createReceipt(Id linkedEntityId) {
        ContentVersion cv = new ContentVersion();
        cv.title = 'receipt-012345';      
        cv.PathOnClient ='test';           
        cv.VersionData = Blob.valueOf('Test File Body');         
        insert cv;

        ContentVersion cvRefreshed = [SELECT Id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink cdl = agrec.TestDataFactory.createContentDocumentLink(
            linkedEntityId,
            cvRefreshed.ContentDocumentId
        );
        insert cdl;
        return cdl;
    }

}